repository:
  topics:
    - data-engineering
    - artificial-intelligence
    - llm
    - rag
    - python
    - databricks
    - sports-analytics
    - football-analytics
    - fastapi
    - react
    - aws
    - gcp
    - portfolio
